development:
  admin_first_name: Firstname
  admin_last_name: Lastname
  admin_email: you@domain.com
  admin_password: password
  domain_name: localhost:3000
  stripe_api_key:
  stripe_publishable_key:
  secret_key_base: # generate your own with `rails secret`

  # AWS stuff
  aws_access_key_id:
  aws_secret_access_key:
  aws_region:
  aws_bucket:

  trial_period: 1209600 # 14 days

test:
  secret_key_base: # generate your own with `rails secret`

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
